apiVersion: v1
kind: Pod
metadata:
  name: hey-loadtest
  namespace: workshop
  labels:
    app: hey
spec:
  containers:
  - name: hey
    image: williamyeh/hey:latest
    command: ["sleep", "3600"]
  restartPolicy: Never
